# -*- coding: utf-8 -*-
"""Revisao_Lists_04_Subconjuntos_Copia.ipynb

Automatically generated by Colaboratory.

# **Revisão de 'list' - Parte 4: Manipulação simultânea de vários elementos**
"""

# 04.1 - Extração de um subconjunto ('slice') de elementos da lista
print("04.1 - Extração de um subconjunto ('slice') de elementos da lista")
moveis_todos = ['cadeira','sofá','mesa','cama']
moveis_parte = moveis_todos[0:2]
print('A lista toda  possui  ' + str(len(moveis_todos)) +' elementos: ',end='')
print(moveis_todos)
print('Subconjunto [0:2] tem ' + str(len(moveis_parte)) +' elementos: ',end='')
print(moveis_parte)
print('\n')

# 04.2 - Extração de subconjunto ('slice') - variantes
print("04.2 - Extração de subconjunto ('slice') - variantes")
moveis_todos = ['cadeira','sofá','mesa','cama']
moveis_p_1   = moveis_todos[:2]
moveis_p_2   = moveis_todos[1:3]
moveis_p_3   = moveis_todos[2:]
print('A lista toda  possui  ' + str(len(moveis_todos)) +' elementos: ',end='')
print(moveis_todos)
print('Subconjunto [:2]  tem ' + str(len(moveis_p_1)) +' elementos: ',end='')
print(moveis_p_1)
print('Subconjunto [1:3] tem ' + str(len(moveis_p_2)) +' elementos: ',end='')
print(moveis_p_2)
print('Subconjunto [2:]  tem ' + str(len(moveis_p_3)) +' elementos: ',end='')
print(moveis_p_3)
print('\n')

# 04.3 - Cópia de toda a lista - CORRETA
print("04.3 - Cópia de toda a lista - CORRETA")
moveis_original     = ['cadeira','sofá','mesa','cama']
moveis_copia_ok     = moveis_original[:]
print('A lista original possui ' + str(len(moveis_original)) +' elementos: ',end='')
print(moveis_original)
print('A cópia ok da lista tem ' + str(len(moveis_copia_ok)) +' elementos: ',end='')
print(moveis_copia_ok)
moveis_original.append('poltrona')
print('A lista original foi alterada para ' + str(len(moveis_original)) +' elementos: ',end='')
print(moveis_original)
print('A copia ok da lista manteve-se com ' + str(len(moveis_copia_ok)) +' elementos: ',end='')
print(moveis_copia_ok)
print('\n')

# 04.4 - Cópia de toda a lista - ERRADA
print("04.4 - Cópia de toda a lista - ERRADA")
moveis_original     = ['cadeira','sofá','mesa','cama']
moveis_copia_nao_ok = moveis_original
print('A lista original possui     ' + str(len(moveis_original)) +' elementos: ',end='')
print(moveis_original)
print('A cópia não ok da lista tem ' + str(len(moveis_copia_nao_ok)) +' elementos: ',end='')
print(moveis_copia_nao_ok)
moveis_original.append('poltrona')
print('A lista original foi alterada para ' + str(len(moveis_original)) +' elementos: ',end='')
print(moveis_original)
print('A copia nao ok da lista ficou com  ' + str(len(moveis_copia_nao_ok)) +' elementos: ',end='')
print(moveis_copia_nao_ok)
print('\n')