# -*- coding: utf-8 -*-
"""Revisao_Lists_01_Criacao_Exibicao_Ordenacao.ipynb

Automatically generated by Colaboratory.

# **Revisão de 'list' - Parte 1: Criação, exibição, inversão, ordenação**
"""

# 01.1 - Criação e exibição de uma lista homogênea
print('01.1 - Criação e exibição de uma lista homogênea')
moveis_1 = ['cadeira','sofá','mesa']
print(moveis_1)
print('\n')

# 01.2 - Criação e exibição de uma lista não homogênea
print('01.2 - Criação e exibição de uma lista não homogênea')
moveis_2 = [1,'cadeira',2,'sofá',3,'mesa',2.5,True]
print(moveis_2)
print('\n')

# 01.3 - Criação e exibição de uma lista homogênea com 'for'
print("01.3 - Criação e exibição de uma lista homogênea com 'for'")
moveis_3 = ['cadeira','sofá','mesa']
for m in moveis_3:
	print('Em casa temos ' + m)
print('\n')

# 01.4 - Criação e exibição de uma lista homogênea, elemento por elemento
print('01.4 - Criação e exibição de uma lista homogênea, elemento por elemento')
moveis_4 = ['cadeira','sofá','mesa']
print('O primeiro móvel de minha lista é: ' + moveis_4[0])
print('O segundo  móvel de minha lista é: ' + moveis_4[1])
print('O terceiro móvel de minha lista é: ' + moveis_4[2])
print('O último   móvel de minha lista é: ' + moveis_4[-1])
print('\n')

# 01.5 - Enumeração de lista homogênea
print('01.5 - Enumeração de lista homogênea')
moveis_5 = ['cadeira','sofá','mesa']
for posicao, m in enumerate(moveis_5):
	print('Em casa temos em ' + str(posicao+1) + 'o. lugar: ' + m)
print('\n')

# 01.6 - Inversão das posições dos elementos de lista homogênea
print('01.6 - Inversão das posições dos elementos de lista homogênea')
moveis_6 = ['cadeira','sofá','mesa']
print('Lista original : ',moveis_6)
moveis_6.reverse()
print('Lista invertida: ',moveis_6)
print('\n')

# 01.7 - Ordenação alfabética 'física' dos elementos de lista homogênea
print("01.7 - Ordenação alfabética 'física' dos elementos de lista homogênea")
moveis_7 = ['cadeira','sofá','mesa']
print('Lista original : ',moveis_7)
moveis_7.sort()
print('Lista ordenada : ',moveis_7)
print('\n')

# 01.8 - Ordenação alfabética 'lógica' (ou 'virtual') dos elementos de lista homogênea
print("01.8 - Ordenação alfabética 'lógica' (ou 'virtual') dos elementos de lista homogênea")
moveis_8 = ['cadeira','sofá','mesa']
print('Lista original antes  da ordenação lógica: ',moveis_8)
print('Resultado da ordenação...')
for posicao, m in enumerate(sorted(moveis_8)):
	print('Em casa temos em ' + str(posicao+1) + 'o. lugar: ' + m)
print('Lista original depois da ordenação lógica: ',moveis_8)
print('\n')

# 01.9 - Ordenação alfabética inversa 'lógica' (ou 'virtual') dos elementos de lista homogênea
print("01.9 - Ordenação alfabética inversa 'lógica' (ou 'virtual') dos elementos de lista homogênea")
moveis_9 = ['cadeira','sofá','mesa']
print('Lista original antes  da ordenação lógica inversa: ',moveis_9)
print('Resultado da ordenação...')
for posicao, m in enumerate(sorted(moveis_9,reverse=True)):
	print('Em casa temos em ' + str(posicao+1) + 'o. lugar: ' + m)
print('Lista original depois da ordenação lógica inversa: ',moveis_9)
print('\n')