# -*- coding: utf-8 -*-
"""Revisao_Lists_05_Numeros.ipynb

Automatically generated by Colaboratory.

# **Revisão de 'list' - Parte 5: Listas com Números**
"""

# 05.1 - Construção automática de uma lista de números com 'range' - Exemplo 1
print("05.1 - Construção automática de uma lista de números com 'range' - Exemplo 1")
lst_nums = range(1,10)
print('A lista toda  possui  ' + str(len(lst_nums)) +' elementos: ',end='')
for n in lst_nums:
	print(n,' ',end='')
print('\n')

# 05.2 - Construção automática de uma lista de números com 'range' - Exemplo 2
print("05.1 - Construção automática de uma lista de números com 'range' - Exemplo 2")
lst_nums = range(1,20,2)
print('A lista toda  possui  ' + str(len(lst_nums)) +' elementos: ',end='')
for n in lst_nums:
	print(n,' ',end='')
print('\n')

# 05.3 - Construção automática de uma lista de números com 'range' - Exemplo 3
print("05.3 - Construção automática de uma lista de números com 'range' - Exemplo 3")
lst_nums = list(range(1,1001))
print('A lista toda  possui  ' + str(len(lst_nums)) +' elementos, mas vamos imprimir somente os últimos...')
for n in lst_nums[-5:]:
	print(n,' ',end='')
print('\n')

# 05.4 - Construção automática de uma lista de números com 'range' - Exemplo 4
print("05.4 - Construção automática de uma lista de números com 'range' - Exemplo 4")
lst_nums = [number*2 for number in range(1,11)]
print('A lista toda  possui  ' + str(len(lst_nums)) +' elementos e todos eles são números pares...')
for n in lst_nums:
	print(n,' ',end='')
print('\n')

# 05.5 - Funções aplicadas sobre os conteúdos dos elementos da lista de números
print("05.5 - Funções aplicadas sobre os conteúdos dos elementos da lista de números")
lst_nums = [30, 67, 12, 44, 95, 28, 79]
print('A lista toda  possui  ' + str(len(lst_nums)) +' elementos: ',end='')
for n in lst_nums:
	print(n,' ',end='')
print('\n')
print('O maior conteúdo da lista é    : ' + str(max(lst_nums)))
print('O menor conteúdo da lista é    : ' + str(min(lst_nums)))
print('A soma dos conteúdos da lista é: ' + str(sum(lst_nums)))
print('\n')