# -*- coding: utf-8 -*-
"""Revisao_Lists_07_Tuplas.ipynb

Automatically generated by Colaboratory.

# **Revisão de 'list' - Parte 7: Listas x Tuplas**
"""

# 07.1 - Uma tupla é imutável (não pode ser alterada, quer em tamanho, quer em conteúdo)
print("07.1 - Uma tupla é imutável (não pode ser alterada, quer em tamanho, quer em conteúdo")
tup_1 = ('Carlos','Sérgio','Djalma')
for e in tup_1:
	print(e,'é professor da FATEC.')
print('Desses nomes,',tup_1[0],'é o primeiro e',tup_1[-1],'é o último.')
print('\n')

# 07.2 - Um placeholder permite formatar uma saída de dados
print("07.2 - Um placeholder permite formatar uma saída de dados")
qtd = 5
print( 'CONCATENAÇÃO: Carlos é professor de ' + str(qtd) + ' disciplinas.')
print( 'SEPARAÇÃO   : Carlos é professor de',qtd,'disciplinas.')
print( 'PLACEHOLDER : Carlos é professor de %d disciplinas.' %qtd)
print(f'FORMAT      : Carlos é professor de {qtd} disciplinas.')
print( 'FORMAT      : Carlos é professor de {} disciplinas.'.format(qtd))
print( 'FORMAT      : Carlos é professor de {0} disciplinas.'.format(qtd))
print( 'FORMAT      : Carlos é professor de {q} disciplinas.'.format(q = qtd))
print('\n')

# 07.3 - Um placeholder permite formatar uma saída de dados - outro exemplo
print("07.3 - Um placeholder permite formatar uma saída de dados - outro exemplo")
nome = 'Carlos'
qtd  = 5
print('CONCATENAÇÃO: ' + nome + ' é professor de ' + str(qtd) + ' disciplinas.')
print('SEPARAÇÃO   :',nome,'é professor de',qtd,'disciplinas.')
print('PLACEHOLDER : %s é professor de %d disciplinas.' %(nome,qtd))
print(f'FORMAT      : {nome} é professor de {qtd} disciplinas.')
print('FORMAT      : {} é professor de {} disciplinas.'.format(nome,qtd))
print('FORMAT      : {0} é professor de {1} disciplinas.'.format(nome,qtd))
print('FORMAT      : {p} é professor de {q} disciplinas.'.format(q=qtd,p=nome))
print('\n')

# 07.4 - Uso de placeholder com tupla de dados
print("07.4 - Uso de placehplder com tupla de dados")
tup_4 = ('Carlos','Sérgio','Djalma')
print('Os professores da FATEC são %s, %s e %s.' %tup_4)
print('\n')

# 07.5 - Lista de tuplas
print("07.5 - Lista de tuplas")
lst_5 = [('Carlos','ED','3p',80),('Sérgio','BD','4p',80)]
print('A lista de tuplas: ', lst_5)
print('Acesso à primeira tupla da lista: ', lst_5[0])
lst_5.append(('Maura','IN','1p',40))
print('Lista após o append de uma tupla: ', lst_5)
lst_5.sort()
print('Lista ordenada: ',lst_5)
print('Resultado de uma busca na lista de tuplas: ', lst_5.index(('Carlos','ED','3p',80)))
for e in lst_5:
	print('Na lista, cada tupla tem os seguintes dados: %s (nome), %s (disciplina),  %s (período) e %d (carga horária).' %e)
print('\n')
lst_5.reverse()
print('Lista em ordem reversa: ',lst_5)