# -*- coding: utf-8 -*-
"""Revisao_Lists_02_Acesso.ipynb

Automatically generated by Colaboratory.

# **Revisão de 'list' - Parte 2: Acesso aos elementos**
"""

# 02.1 - Modificação de um elemento da lista
print('02.1 - Modificação de um elemento da lista')
moveis_1    = ['cadeira','mesa','sofá']
print('Antes : ' + str(moveis_1))
moveis_1[0] = 'cama'
print('Depois: ' + str(moveis_1))
print('\n')

# 02.2 - Busca por um conteúdo dentre os elementos de uma lista
print('02.2 - Busca por um conteúdo dentre os elementos de uma lista')
moveis_2 = ['cadeira','mesa','sofá']
print(moveis_2)
print('Procurando cadeira: existe na lista, na posição ',end='')
print(moveis_2.index('cadeira'))
print('Procurando cama: não existe na lista')
# comentar a linha abaixo se quiser evitar erro
print(moveis_2.index('cama'))
print('\n')

# 02.3 - Verificação de existência de um conteúdo dentre os elementos de uma lista
print('02.3 - Verificação de existência de um conteúdo dentre os elementos de uma lista')
moveis_2 = ['cadeira','mesa','sofá']
print(moveis_2)
print('Procurando mesa: ',end='')
if 'mesa' in moveis_2:
	print('existe na lista, na posição ',moveis_2.index('mesa'))
else:
	print('não existe na lista ...')
print('Procurando cama: ',end='')
if 'cama' in moveis_2:
	print('existe na lista, na posição ',moveis_2.index('cadeira'))
else:
	print('não existe na lista ...')
print('\n')